// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-c2UrKAAMEZzauSyR-TNUflyfU9bpzvQ',
    appId: '1:83626215267:web:acc7e1df9689bc8b93f556',
    messagingSenderId: '83626215267',
    projectId: 'pureskinai-d4100',
    authDomain: 'pureskinai-d4100.firebaseapp.com',
    storageBucket: 'pureskinai-d4100.firebasestorage.app',
    measurementId: 'G-4B25546EHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuNbywQhrlvQkmTu8XZQn96gPP78EIYlI',
    appId: '1:83626215267:android:e0c2767d5c3ab81693f556',
    messagingSenderId: '83626215267',
    projectId: 'pureskinai-d4100',
    storageBucket: 'pureskinai-d4100.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDagseLCxTchBoVHlICCBzmHMjlqEqbrzo',
    appId: '1:83626215267:ios:12df1d15a785cbcf93f556',
    messagingSenderId: '83626215267',
    projectId: 'pureskinai-d4100',
    storageBucket: 'pureskinai-d4100.firebasestorage.app',
    iosBundleId: 'com.example.pureSkinAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDagseLCxTchBoVHlICCBzmHMjlqEqbrzo',
    appId: '1:83626215267:ios:12df1d15a785cbcf93f556',
    messagingSenderId: '83626215267',
    projectId: 'pureskinai-d4100',
    storageBucket: 'pureskinai-d4100.firebasestorage.app',
    iosBundleId: 'com.example.pureSkinAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-c2UrKAAMEZzauSyR-TNUflyfU9bpzvQ',
    appId: '1:83626215267:web:34cccfbcf2ebb97d93f556',
    messagingSenderId: '83626215267',
    projectId: 'pureskinai-d4100',
    authDomain: 'pureskinai-d4100.firebaseapp.com',
    storageBucket: 'pureskinai-d4100.firebasestorage.app',
    measurementId: 'G-0PXGD7257Z',
  );
}
